#############
# ToolSquare CI script
# Doc: https://gitlab-ncsa.ubisoft.org/ToolSquare/docs/wikis/built-in-scripts-documentation
# Source code: https://gitlab-ncsa.ubisoft.org/ToolSquare/ToolSquareScripts/tree/master/Scripts/GitLabCI/Macros

stages:
  - build
  - test
  - deploy
  - analysis

#############
# Stage Build: compile the solution on all targets, keep the binaries for further steps.

compilation:debug:
  stage: build
  script:
  - TeaBox.com Build -solutionFile=Sharpmake.sln -configuration="Debug|Any CPU"
  artifacts:
    paths:
    - Sharpmake.Application/bin/Debug/
    - Sharpmake.UnitTests/bin/Debug/
    - samples/ConfigureOrder/bin/Debug/
    - samples/CPPCLI/bin/Debug/
    - samples/CSharpHelloWorld/bin/Debug/
    - samples/CSharpVsix/bin/Debug/
    - samples/Dependencies/bin/Debug/
    - samples/HelloWorld/bin/Debug/
    - samples/MultiPlatform/bin/Debug/
    - samples/PackageReferences/bin/Debug/
    - samples/SharpmakeGen/bin/Debug/
    - samples/SimpleExeLibDependency/bin/Debug/
    expire_in: 1 hour

compilation:release:
  stage: build
  script:
  - TeaBox.com Build -solutionFile=Sharpmake.sln -configuration="Release|Any CPU"
  artifacts:
    paths:
    - Sharpmake.Application/bin/Release/
    expire_in: 1 hour

#############
# Stage Test: 
#  -Run all unit tests
#  -Launch regression tests

unit_test:
  stage: test
  script:
  - TeaBox.com RunTests -solutionFile=Sharpmake.sln -configuration="Debug|Any CPU"
  dependencies:
  - compilation:debug

regression_test:
  stage: test
  script:
  - call python regression_test.py
  dependencies:
  - compilation:debug

#############
# Stage Deploy: 
#  -Deploy the tagged versions into nuget and create facades
#  -Host binaries in GitLab too

sharpmake_facades:
  stage: deploy
  script:
  - TeaBox.com PublishNugetPackage -csprojFile="Sharpmake.Application/Sharpmake.Application.csproj" -generateFacades=true -configuration="Release|Any CPU"
  artifacts:
    name: Sharpmake_Facades_%CI_BUILD_TAG%
    paths:
    - GeneratedFacades/*
  only:
  - tags
  dependencies:
  - compilation:release

sharpmake_binaries:
  stage: deploy
  script:
  - echo "Uploaded artifacts"
  artifacts:
    name: Sharpmake_%CI_BUILD_TAG%
    paths:
    - Sharpmake.Application/bin/Release/
    expire_in: 1 year
  only:
  - tags
  dependencies:
  - compilation:release
  
#############
# Stage Analysis: Run a full SonarQube analysis on the code base.

sonarqube_analysis:  
  stage: analysis
  script:
  - TeaBox.com AnalyseCode -solutionFile=Sharpmake.sln
  only:
  - tags
