os: Visual Studio 2015

platform:
  - Win32

before_build:
  - cmd: git clean -ffxd

build_script:
  - cmd: nuget restore Sharpmake.sln
  - cmd: echo "Building..." && "%VS140COMNTOOLS%\..\IDE\devenv.com" /Build "Release" Sharpmake.sln
