os: Visual Studio 2015

version: 0.0.{build}

before_build:
  - cmd: git clean -ffxd
  - cmd: nuget restore Sharpmake.sln

build_script:
  - cmd: echo "Building..." && "%VS140COMNTOOLS%\..\IDE\devenv.com" /Build "Release" Sharpmake.sln

test_script:
  - cmd: nunit3-console Sharpmake.UnitTests\bin\release\Sharpmake.UnitTests.dll --result=myresults.xml;format=AppVeyor

artifacts:
  - path: Sharpmake.Application\bin\release\Sharpmake.Application.exe
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.Application.exe.config
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.Application.pdb
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.CommonPlatforms.dll
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.CommonPlatforms.pdb
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.dll
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.pdb
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.Generators.dll
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\Sharpmake.Generators.pdb
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\SimpleNuGet.dll
    name: Sharpmake
  - path: Sharpmake.Application\bin\release\SimpleNuGet.pdb
    name: Sharpmake